import { Company, Director } from "@/types";

export const sampleCompanies: Company[] = [
  {
    id: "cmp-1",
    cin: "U12345MH2019PTC123456",
    name: "Acme Corp Pvt Ltd",
    incorpDate: "2019-01-01",
    category: "Company limited by Shares",
    class: "Private",
    subcategory: "Non-govt company",
    fyStart: "04-01",
    fyEnd: "03-31",
    country: "India",
    state: "Maharashtra",
    city: "Mumbai",
    pinCode: "400001",
    rocJurisdiction: "Mumbai",
    branches: [],
    corporateRelations: [],
    registrations: { pan: "ABCDE1234F", tan: "MUM12345A" },
  },
  {
    id: "cmp-2",
    cin: "L98765KA2018PLC654321",
    name: "Beta Industries Ltd",
    incorpDate: "2018-05-20",
    category: "Company limited by Shares",
    class: "Public",
    subcategory: "Non-govt company",
    fyStart: "04-01",
    fyEnd: "03-31",
    country: "India",
    state: "Karnataka",
    city: "Bangalore",
    pinCode: "560001",
    rocJurisdiction: "Bangalore",
    branches: [],
    corporateRelations: [],
    registrations: { pan: "FGHIJ5678K", tan: "BNG54321B" },
  },
  {
    id: "cmp-3",
    cin: "O54321TN2020OPC112233",
    name: "Gamma One Person Company",
    incorpDate: "2020-11-11",
    category: "Company limited by Shares",
    class: "OPC",
    subcategory: "Non-govt company",
    fyStart: "04-01",
    fyEnd: "03-31",
    country: "India",
    state: "Tamil Nadu",
    city: "Chennai",
    pinCode: "600002",
    rocJurisdiction: "Chennai",
    branches: [],
    corporateRelations: [],
    registrations: { pan: "KLMNO9012L", tan: "CHN21098C" },
  },
];

export const sampleDirectors: Director[] = [
  {
    id: "dir-1",
    prefix: "Mr",
    first_name: "Rajesh",
    middle_name: "Kumar",
    last_name: "Sharma",
    din: "12345678",
    email: "rajesh.sharma@email.com",
    phone_number: "+91-9876543210",
    designation: "Managing Director",
    designation_category: "Promoter",
    designation_subcategory: "Executive Director",
    nationality: "Indian",
    occupation: "Business",
    date_of_birth: "1975-05-15",
    date_of_appointment: "2020-01-01",
    present_address: "123 Business District, Mumbai",
    present_city: "Mumbai",
    present_state: "Maharashtra",
    present_country: "India",
    present_pin_code: "400001",
    has_interest_in_other_entities: true,
    other_entities: [
      {
        id: "entity-1",
        entity_name: "Sharma Industries Pvt Ltd",
        registration_number: "U12345MH2019PTC123456",
        designation: "Director",
        date_of_appointment: "2019-06-01",
        shareholding_percentage: 25.5,
        shareholding_amount: 2550000,
      },
    ],
    companies: [],
  },
  {
    id: "dir-2",
    prefix: "Ms",
    first_name: "Priya",
    last_name: "Patel",
    din: "87654321",
    email: "priya.patel@email.com",
    phone_number: "+91-9123456789",
    designation: "Director",
    designation_category: "Independent",
    designation_subcategory: "Non-Executive Director",
    nationality: "Indian",
    occupation: "Chartered Accountant",
    date_of_birth: "1980-08-22",
    date_of_appointment: "2021-03-15",
    present_address: "456 Finance Street, Delhi",
    present_city: "Delhi",
    present_state: "Delhi",
    present_country: "India",
    present_pin_code: "110001",
    has_interest_in_other_entities: false,
    other_entities: [],
    companies: [],
  },
  {
    id: "dir-3",
    prefix: "Dr",
    first_name: "Amit",
    middle_name: "Singh",
    last_name: "Verma",
    din: "11223344",
    email: "amit.verma@email.com",
    phone_number: "+91-9988776655",
    designation: "Chief Executive Officer",
    designation_category: "Professional",
    designation_subcategory: "Executive Director",
    nationality: "Indian",
    occupation: "Management Professional",
    date_of_birth: "1978-12-10",
    date_of_appointment: "2022-01-01",
    present_address: "789 Corporate Avenue, Bangalore",
    present_city: "Bangalore",
    present_state: "Karnataka",
    present_country: "India",
    present_pin_code: "560001",
    has_interest_in_other_entities: true,
    other_entities: [
      {
        id: "entity-2",
        entity_name: "Tech Ventures LLP",
        registration_number: "AAB-1234",
        designation: "Partner",
        date_of_appointment: "2020-05-15",
        shareholding_percentage: 15.0,
        shareholding_amount: 1500000,
      },
    ],
    companies: [],
  },
];
