// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmrionldfmdhtqfnksyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tcmlvbmxkZm1kaHRxZm5rc3l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTUyOTYsImV4cCI6MjA2MzczMTI5Nn0.77kNIaimjSlaDBc5t-GZ2aEWkUyJHMmijkM_wxJaKwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);